import { StyleSheet } from 'react-native';
import { colors, typography } from '../../../../shared/styles';

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalView: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 20,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryLight,
  },
  modalTitle: {
    ...typography.styles.h3,
    color: colors.text.primary,
    fontWeight: '700',
  },
  closeButton: {
    padding: 8,
    backgroundColor: colors.primaryLight,
    borderRadius: 30,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formContainer: {
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 18,
  },
  medicalInfoContainer: {
    backgroundColor: colors.surfaceVariant,
    borderRadius: 16,
    paddingHorizontal: 6,
    paddingTop: 4,
    paddingBottom: 6,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    marginTop: 4,
  },
  inputLabel: {
    ...typography.styles.caption,
    color: colors.text.secondary,
    marginBottom: 6,
    fontWeight: '600',
    marginLeft: 4,
  },
  medicalInfoTitle: {
    ...typography.styles.caption,
    color: colors.text.secondary,
    marginBottom: 6,
    fontWeight: '600',
    marginLeft: 4,
  },
  medicalInfoCaption: {
    ...typography.styles.small,
    color: colors.text.secondary,
    marginBottom: 10,
    marginLeft: 4,
    fontStyle: 'italic',
  },
  input: {
    height: 44,
    borderWidth: 1,
    borderColor: colors.border.light,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
    color: colors.text.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  edadContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  edadInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border.light,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
    color: colors.text.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  unidadSelector: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceVariant,
    borderRadius: 12,
    padding: 2,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  unidadButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    minWidth: 60,
    alignItems: 'center',
  },
  unidadButtonActive: {
    backgroundColor: colors.button.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  unidadButtonText: {
    ...typography.styles.caption,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  unidadButtonTextActive: {
    color: colors.text.primary,
    fontWeight: '700',
  },
  textArea: {
    height: 100,
    paddingTop: 12,
    paddingBottom: 12,
    textAlignVertical: 'top',
  },
  checkboxContainer: {
    marginVertical: 10,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  checkboxText: {
    flex: 1,
    ...typography.styles.body,
    color: colors.text.primary,
  },
  checkboxDescription: {
    ...typography.styles.small,
    color: colors.text.secondary,
    marginLeft: 24,
    marginTop: 2,
  },
  guardarButton: {
    backgroundColor: colors.button.primary,
    borderRadius: 100,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  guardarButtonText: {
    ...typography.styles.button,
    color: colors.text.primary,
    fontWeight: '700',
  },
  
  // Estilos para validación
  inputError: {
    borderColor: colors.error,
    borderWidth: 2,
  },
  errorText: {
    ...typography.styles.small,
    color: colors.error,
    marginTop: 4,
    marginLeft: 4,
    fontWeight: '500',
  },
});
