import { StyleSheet } from "react-native";
import { colors, typography } from "../../../shared/styles";

export const styles = StyleSheet.create({
    container: { 
      flexGrow: 1, 
      backgroundColor: colors.background, 
      padding: 24,
      paddingTop: 50,
    },
    title: { 
      fontSize: 28, 
      fontFamily: typography.fontFamily.title,
      marginBottom: 24, 
      marginTop: 30,
      color: colors.brand.highlight,
      textAlign: "center",
    },
    input: {
      borderWidth: 1.5,
      borderColor: colors.border.light,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      backgroundColor: colors.surface,
      fontSize: 15,
      fontFamily: typography.fontFamily.body,
      color: colors.text.primary,
    },
    inputError: {
      borderColor: colors.error,
      borderWidth: 1.5,
    },
    dateInput: {
      justifyContent: 'center',
    },
    dateText: {
      fontSize: 15,
      fontFamily: typography.fontFamily.body,
      color: colors.text.primary,
    },
    datePlaceholder: {
      fontSize: 15,
      fontFamily: typography.fontFamily.body,
      color: '#999',
    },
    errorText: {
      color: colors.error,
      fontSize: 12,
      fontFamily: typography.fontFamily.body,
      marginBottom: 8,
      marginTop: -8,
    },
    subtitle: { 
      fontSize: 16, 
      fontFamily: typography.fontFamily.bodySemiBold,
      marginTop: 16, 
      marginBottom: 8,
      color: colors.text.primary,
    },
    picker: {
      borderWidth: 1.5,
      borderColor: colors.border.light,
      borderRadius: 12,
      marginBottom: 12,
      backgroundColor: colors.surface,
    },
    clipButton: {
      borderWidth: 1.5,
      borderColor: colors.border.light,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
      backgroundColor: colors.surfaceVariant,
    },
    clipButtonError: {
      borderColor: colors.error,
      borderWidth: 1.5,
    },
    clipText: {
      color: colors.text.primary,
      fontSize: 15,
      fontFamily: typography.fontFamily.body,
    },
    reminderText: {
      color: colors.text.secondary,
      fontSize: 12,
      fontFamily: typography.fontFamily.body,
      fontStyle: "italic",
      marginBottom: 8,
      marginTop: -4,
      lineHeight: 16,
    },
    buttonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 24,
      gap: 12,
    },
    button: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 24,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    cancel: { 
      backgroundColor: colors.surface,
      borderWidth: 2,
      borderColor: colors.brand.highlight,
    },
    continue: { 
      backgroundColor: colors.brand.highlight,
    },
    cancelText: { 
      color: colors.brand.highlight, 
      fontFamily: typography.fontFamily.bodySemiBold,
      fontSize: 15,
    },
    continueText: { 
      color: colors.text.inverse, 
      fontFamily: typography.fontFamily.bodySemiBold,
      fontSize: 15,
    },
    infoText: {
      color: colors.text.secondary,
      fontSize: 12,
      fontFamily: typography.fontFamily.body,
      textAlign: "center",
      marginTop: 24,
      marginBottom: 20,
      fontStyle: "italic",
      lineHeight: 18,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingTop: 20,
      paddingBottom: 40,
      maxHeight: "50%",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.light,
    },
    modalTitle: {
      fontSize: 18,
      fontFamily: typography.fontFamily.title,
      color: colors.text.primary,
    },
    modalCloseButton: {
      fontSize: 16,
      fontFamily: typography.fontFamily.bodySemiBold,
      color: colors.brand.highlight,
    },
    modalOptionsContainer: {
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    modalOption: {
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 12,
      marginBottom: 12,
      backgroundColor: colors.surfaceVariant,
      borderWidth: 1.5,
      borderColor: colors.border.light,
    },
    modalOptionSelected: {
      backgroundColor: colors.brand.highlight,
      borderColor: colors.brand.highlight,
    },
    modalOptionText: {
      fontSize: 16,
      fontFamily: typography.fontFamily.body,
      color: colors.text.primary,
      textAlign: 'center',
    },
    modalOptionTextSelected: {
      color: colors.text.inverse,
      fontFamily: typography.fontFamily.bodySemiBold,
    },
  });
  